//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABA2_SERVER_PART
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOMS_CLIENTS
    {
        public Nullable<int> ROOM_ID { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public int ID { get; set; }
    
        public virtual CLIENTS CLIENTS { get; set; }
        public virtual ROOM ROOM { get; set; }
    }
}
